#!/bin/bash

declare -a CONFIG_KEYS=(
    "user.name"
    "user.email"
    "user.signingkey"
    "commit.gpgSign"
    "merge.verifySignatures"
    )

for i in "${CONFIG_KEYS[@]}"
do
    VAL=$(git config --get "$i")

    if [ -z "$VAL" ]; then
        echo "$i is not configured, quit ..."
        exit 1
    fi
done
